import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Nunito } from "next/font/google";
import ClientOnly from "@/components/ClientOnly";
import Modal from "@/components/modals/Modal";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Next 13 Airbnb clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <Modal isOpen={true} />
          <Navbar />
        </ClientOnly>

        {children}
      </body>
    </html>
  );
}
